import React from 'react'
import HeaderComponent from '../components/Header';
import FooterComponent from '../components/Footer';
import Head from 'next/head'


type MainLayoutProps = {
  children:
  | JSX.Element
  | JSX.Element[]
  | string
  | string[];
}

const MainLayout: React.FC<MainLayoutProps> = ({ children }) => {
  return (
    <div className='flex flex-col justify-between h-screen'>
      <Head>
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&display=swap" rel="stylesheet" />
        <title>bloowatch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://www.bloowatch.com/hubfs/Bloowatch_Jan2017/images/favicon%20(1).ico" />
      </Head>
      <HeaderComponent />
      <div className="w-9/12 mx-auto">
        {children}
      </div>
      <FooterComponent />
    </div>
  )
}

export default MainLayout;
